name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/arm64/containerd.io_1.6.28-1_arm64.deb
          wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/arm64/docker-ce_25.0.3-1~debian.11~bullseye_arm64.deb
          wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/arm64/docker-ce-cli_25.0.3-1~debian.11~bullseye_arm64.deb
          wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/arm64/docker-compose-plugin_2.14.1~debian-bullseye_arm64.deb

      - name: Install Docker Packages
        run: |
          sudo dpkg -i containerd.io_1.6.28-1_arm64.deb \
                       docker-ce_25.0.3-1~debian.11~bullseye_arm64.deb \
                       docker-ce-cli_25.0.3-1~debian.11~bullseye_arm64.deb \
                       docker-compose-plugin_2.14.1~debian-bullseye_arm64.deb


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to my registry
        uses: docker/login-action@v3
        with:
          registry: git.everythingisart.org
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            git.everythingisart.org/everythingisart/spotifyjourneyjams:latest
            git.everythingisart.org/everythingisart/spotifyjourneyjams:0.3   