name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_and_push:
    runs-on: docker
    steps:
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E apt-key add -
          sudo echo "deb https://deb.nodesource.com/node_14.x $(lsb_release -cs) main" > /etc/apt/sources.list.d/nodesource.list
          sudo echo "deb-src https://deb.nodesource.com/node_14.x $(lsb_release -cs) main" >> /etc/apt/sources.list.d/nodesource.list
          sudo apt-get update -y
          sudo apt-get install -y nodejs

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to my registry
        uses: docker/login-action@v3
        with:
          registry: git.everythingisart.org
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            git.everythingisart.org/everythingisart/spotifyjourneyjams:latest
            git.everythingisart.org/everythingisart/spotifyjourneyjams:0.3   