name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Ubuntu Version, Architecture, and Docker Version
        id: docker_info
        run: |
          UBUNTU_VERSION=$(lsb_release -cs)
          ARCH=$(dpkg --print-architecture)
          VERSION=$(curl -sSL https://download.docker.com/linux/ubuntu/dists/${UBUNTU_VERSION}/pool/stable/ | grep -oP '(?<=docker-ce_)\d+\.\d+\.\d+(?=_${ARCH})' | head -n1)
          echo "::set-output name=UBUNTU_VERSION::${UBUNTU_VERSION}"
          echo "::set-output name=ARCH::${ARCH}"
          echo "::set-output name=VERSION::${VERSION}"

      - name: Download Docker packages
        run: |
          curl -fsSL "https://download.docker.com/linux/ubuntu/dists/${{ steps.docker_info.outputs.UBUNTU_VERSION }}/pool/stable/containerd.io_${{ steps.docker_info.outputs.VERSION }}_${{ steps.docker_info.outputs.ARCH }}.deb" -o containerd.io.deb
          curl -fsSL "https://download.docker.com/linux/ubuntu/dists/${{ steps.docker_info.outputs.UBUNTU_VERSION }}/pool/stable/docker-ce_${{ steps.docker_info.outputs.VERSION }}_${{ steps.docker_info.outputs.ARCH }}.deb" -o docker-ce.deb
          curl -fsSL "https://download.docker.com/linux/ubuntu/dists/${{ steps.docker_info.outputs.UBUNTU_VERSION }}/pool/stable/docker-ce-cli_${{ steps.docker_info.outputs.VERSION }}_${{ steps.docker_info.outputs.ARCH }}.deb" -o docker-ce-cli.deb
          curl -fsSL "https://download.docker.com/linux/ubuntu/dists/${{ steps.docker_info.outputs.UBUNTU_VERSION }}/pool/stable/docker-buildx-plugin_${{ steps.docker_info.outputs.VERSION }}_${{ steps.docker_info.outputs.ARCH }}.deb" -o docker-buildx-plugin.deb
          curl -fsSL "https://download.docker.com/linux/ubuntu/dists/${{ steps.docker_info.outputs.UBUNTU_VERSION }}/pool/stable/docker-compose-plugin_${{ steps.docker_info.outputs.VERSION }}_${{ steps.docker_info.outputs.ARCH }}.deb" -o docker-compose-plugin.deb

      - name: Install Docker packages
        run: |
          sudo dpkg -i ./containerd.io.deb \
            ./docker-ce.deb \
            ./docker-ce-cli.deb \
            ./docker-buildx-plugin.deb \
            ./docker-compose-plugin.deb

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to my registry
        uses: docker/login-action@v3
        with:
          registry: git.everythingisart.org
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            git.everythingisart.org/everythingisart/spotifyjourneyjams:latest
            git.everythingisart.org/everythingisart/spotifyjourneyjams:0.3   