name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker's apt repository
        run: |
          apt-get update -y
          apt-get install -y \
            ca-certificates \
            curl

          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg

      - name: Add the repository to Apt sources
        run: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Update the APT package index
        run: apt-get update -y

      - name: Install Docker CE
        run: apt-get install docker-ce docker-ce-cli containerd.io -y
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to my registry
        uses: docker/login-action@v3
        with:
          registry: git.everythingisart.org
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            git.everythingisart.org/everythingisart/spotifyjourneyjams:latest
            git.everythingisart.org/everythingisart/spotifyjourneyjams:0.3   